cmake_minimum_required(VERSION 3.23)
project(stepit_plugin_policy_neuro_ros2)
set(CMAKE_CXX_STANDARD 17)

# find dependencies
find_package(ament_cmake REQUIRED)

find_package(grid_map_msgs REQUIRED)
find_package(grid_map_ros REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(tf2_ros REQUIRED)

stepit_add_plugin(${PROJECT_NAME})
target_sources(${PROJECT_NAME}
    PRIVATE
      src/base_lin_vel_source.cpp
      src/cmd_posture_subscriber2.cpp
      src/cmd_vel_subscriber2.cpp
      src/depth_history_source.cpp
      src/field_subscriber2.cpp
      src/heightmap_subscriber2.cpp
      src/wbc_command_source.cpp
    PUBLIC
      FILE_SET HEADERS
      BASE_DIRS include
      FILES
        include/stepit/policy_neuro_ros2/base_lin_vel_source.h
        include/stepit/policy_neuro_ros2/cmd_posture_subscriber2.h
        include/stepit/policy_neuro_ros2/cmd_vel_subscriber2.h
        include/stepit/policy_neuro_ros2/depth_history_source.h
        include/stepit/policy_neuro_ros2/field_subscriber2.h
        include/stepit/policy_neuro_ros2/heightmap_subscriber2.h
        include/stepit/policy_neuro_ros2/wbc_command_source.h
)
target_link_libraries(${PROJECT_NAME} PUBLIC
    stepit_core
    stepit_plugin_policy_neuro
    stepit_plugin_ros2_base
)
install(TARGETS ${PROJECT_NAME}
    EXPORT stepitTargets
    LIBRARY DESTINATION ${STEPIT_LIB_DESTINATION}
    ARCHIVE DESTINATION ${STEPIT_LIB_DESTINATION}
    FILE_SET HEADERS DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
ament_target_dependencies(${PROJECT_NAME} PUBLIC
    grid_map_msgs
    grid_map_ros
    nav_msgs
    tf2_ros
)


if (BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif ()

ament_package()
